# Generated by Django 2.2.7 on 2019-11-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(default=None, max_length=30)),
                ('amount', models.PositiveIntegerField(default=None)),
                ('payment_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'OGHBS_Payments',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(default=None, max_length=30, unique=True)),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=False)),
                ('room_type', models.CharField(blank=True, choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC')], max_length=20, null=True)),
                ('booktime', models.DateField()),
                ('guesthouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GuestHouse')),
            ],
            options={
                'db_table': 'OGHBS_Reservation',
                'ordering': ['-booktime'],
            },
        ),
        migrations.CreateModel(
            name='WaitingOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(default=None, max_length=30)),
                ('room_type', models.CharField(choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC')], max_length=20)),
                ('price', models.PositiveIntegerField(default=None)),
                ('services', models.CharField(default='No special services available', max_length=50, null=True)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GuestHouse')),
            ],
            options={
                'db_table': 'OGHBS_Rooms',
                'ordering': ['roomID'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms_allocated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rooms'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundID', models.CharField(default=None, max_length=30)),
                ('amount', models.PositiveIntegerField(default=None)),
                ('refund_time', models.DateTimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='main.Reservation')),
                ('user_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OGHBS_Refunds',
                'ordering': ['-refund_time'],
            },
        ),
        migrations.CreateModel(
            name='PreReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC')], max_length=20, null=True)),
                ('guesthouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GuestHouse')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.Reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackID', models.CharField(default=None, max_length=100)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('feed', models.TextField(default=None)),
                ('user_of', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OGHBS_feedbacks',
                'ordering': ['-time'],
            },
        ),
    ]
