# Generated by Django 2.2.7 on 2019-12-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestdetails',
            options={'verbose_name': 'GuestDetails'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-booktime'], 'verbose_name': 'Reservation'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['roomID'], 'verbose_name': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='waitingon',
            options={'verbose_name': 'WaitingOn'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bookingID',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
