# Generated by Django 2.2.7 on 2019-12-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191206_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestdetails',
            options={'verbose_name_plural': 'GuestDetails'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-booktime'], 'verbose_name_plural': 'Reservation'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['roomID'], 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='waitingon',
            options={'verbose_name_plural': 'WaitingOn'},
        ),
    ]
