# Generated by Django 2.2.7 on 2019-12-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191206_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-booktime']},
        ),
    ]
